apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: git@github.com:ozgureroglu/dev-argocd-applications.git
    targetRevision: main
