apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rke1-cluster-stag-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: stag-env/apps
    repoURL: git@github.com:ozgureroglu/ovh-rke1-root-argocd.git
    targetRevision: main
