apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-env
  namespace: dev-ns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev-ns
    name: in-cluster
  project: default
  source:
    path: envs/dev
    repoURL: git@github.com:ozgureroglu/ovh-rke1-root-argocd.git
    targetRevision: main
