apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-env
  namespace: prod-ns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    path: k8s
    repoURL: git@github.com:ozgureroglu/argocd_test_repo.git
    targetRevision: main
