apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-env
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: envs/stag
    repoURL: git@github.com:ozgureroglu/ovh-rke1-root-argocd.git
    targetRevision: main
