apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-env
  namespace: test-ns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argotest
    name: in-cluster
  project: default
  source:
    path: k8s
    repoURL: git@github.com:ozgureroglu/argocd_test_repo.git
    targetRevision: main
