apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-repo-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-ns
    name: in-cluster
  project: default
  source:
    path: k8s
    repoURL: git@github.com:ozgureroglu/argocd_test_repo.git
    targetRevision: dev
