apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xyz-tenant-01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: qa-tenant-01
    name: in-cluster
  project: default
  source:
    path: k8s
    repoURL: git@github.com:ozgureroglu/argocd_test_repo.git
    targetRevision: stable
